apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
      - name: private
        image: docker.io/mbakalarski/private:dso-demo-multistage
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
